### ISSUE TITLE
Version of EmitterAction where payload is always defined

### ISSUE THREAD

**Issue by IlCallo** [ngxs-labs/emitter#102]
Currently payload into `EmitterAction` has type `T | undefined`.

It would be handy to add a similar default action which does a runtime check about the payload being present and have type `T`, leaving the user to chose what to use.

For now, I just manually typed the payload into the Receiver signature as `{ payload }: { payload: MyType }`

**Comment by splincode** [comment]
Try 
```ts { payload }: EmitterAction<MyType>```

**Comment by splincode** [comment]
doing checks in runtime is bad, you should know at compile time that you give

**Comment by IlCallo** [comment]
Yeah, that's what I tried at first, but payload result as `MyType | undefined`.
It's due to line 15

https://github.com/ngxs-labs/emitter/blob/15ea223d8059577a3df23111be36e1a18eb64a64/src/lib/core/actions/actions.ts#L1-L16

which translates to this type declaration

```ts
/**
 * This class is used as a default action when the user doesn't pass any custom action as an argument
 */
export declare class EmitterAction<T = any> {
    payload?: T | undefined;
    /**
     * Action type
     */
    static type: string | null;
    /**
     * Creates EmitterAction instance
     *
     * @param payload - Data to dispatch
     */
    constructor(payload?: T | undefined);
}
```

But this is probably not the right behaviour, because when we declare a type we expect to get that value.
So implementation should probably be

```ts
/**
 * This class is used as a default action when the user doesn't pass any custom action as an argument
 */
export class EmitterAction<T = any> {
    /**
     * Action type
     */
    public static type: string | null = null;

    /**
     * Creates EmitterAction instance
     *
     * @param payload - Data to dispatch
     */
    constructor(public payload: T) {}
}
```

(notice payload is no more optional)

**Comment by IlCallo** [comment]
> doing checks in runtime is bad, you should know at compile time that you give

Make sense, what about giving the developer full control about the inner type?
(the `EmitterAction<MyType | undefined>` stuff instead of automatically typing the payload as optional)

**Comment by splincode** [comment]
Sorry, but if you want need optional you can try

```ts
{ payload }: EmitterAction<void>

Type check for emit

@Emitter(State.send)
public send: Emittable<void>


this.send.emit()
```

**Comment by IlCallo** [comment]
That's the opposite of what I want ç_ç

I'll try explaining it again.

**How it works now**
I use `EmitterAction<MyType>`, payload property get type `MyType | undefined`

This is due to the constructor being marked as optional, while it probably shouldn't be.

**How it should be (IMHO)**
I use `EmitterAction<MyType>`, payload property get type `MyType`

**Proposed change**
`constructor(public payload?: T) {}` => `constructor(public payload: T) {}`

**Comment by splincode** [comment]
PR please

**Comment by arturovt** [comment]
@IlCallo 
Optional operator (`?`) marks argument as 'might not exist'. Thus it's possible to call constructor without providing any arguments:
```typescript
new EmitterAction()
```
If we remove `?` - basically we will have to pass some argument into constructor:
```typescript
new EmitterAction(undefined);
```
If you're definitely sure that `payload` is typeof `MyType` - then use not-null assertion operator:
```typescript
static someReceiver(ctx: StateContext<SomeState>, { payload }: EmitterAction<MyType>) {
    const copy: MyType = payload! <--;
}
```

**Comment by IlCallo** [comment]
I prefer avoiding not-null assertion operator because it makes my code more easily breakable, I keep it only for business rules I cannot model in other ways.

It's true that then you'll need to call the constructor with `undefined`, but try to think about it from the consumer perspective.
The plugin creates the EmitterAction (I guess) in a single place, when an emission is fired off from `@Emitter` .
On the other side, it seems to me, EmitterAction is used/consumed on `@Receiver` only when there actually is a payload, otherwise it's better to just skip the second parameter.

With payload

```ts
@Receiver()
  public static receiver(
    context: StateContext<boolean>,
    { payload }: EmitterAction<boolean>
  ) { /* stuff using payload, we know the payload type of course */ }
```

Without payload

```ts
@Receiver()
  public static receiver(
    context: StateContext<boolean>
  ) { /* stuff not using payload */ }
```

And when you are using the payload, you probably know what's inside it, so you want to type it as you like.
Putting that `?` to avoid that single (or few) `new EmitterAction(undefined);` in the library code, you are stripping away a freedom degree from developers and forcing all consumers in the more common (only?) use for `EmitterAction` on their side to use a not-null assertion or casting or avoiding using that class altogether.

Btw that's why I proposed to create two different classes in the first place.
So you can keep using `EmitterAction` internally as you like, but consumers have a second implementation exposed where they can type the payload in the right way without dealing with an annoying `undefined`.

**Comment by splincode** [comment]
@IlCallo https://github.com/ngxs-labs/emitter/blob/master/src/lib/core/internal/internals.ts#L30

You can specify the default value in the payload.

```ts
@Emitter(MyState.update)
public update: Emittable<void>;

this.value.emit(); 
```

```ts
@Receiver({ payload: "my_custom_default_value" })
public static update(ctx: StateContext<boolean>, action: EmitterAction<boolean>) {
  console.log(action.payload); // "my_custom_default_value" if emit call with undefined
}
```
