### ISSUE TITLE
Emit action inside an action listener (with ofEmittableXXX) cancel others listeners

### ISSUE THREAD

**Issue by mselerin** [ngxs-labs/emitter#147]
Emitting another action inside one of the `ofEmittable` filter cancel the others subscription.

Example : 

```typescript
this.actions$.pipe(
  ofEmittableSuccessful(SampleState.setValue1),
  tap(() => console.log('Success handler 1'))
).subscribe();

this.actions$.pipe(
  ofEmittableSuccessful(SampleState.setValue1),
  tap(() => console.log('Success handler 2')),
  tap(() => this.emitter.action(SampleState.setValue2).emit(this.rdm()))
).subscribe();

this.actions$.pipe(
  ofEmittableSuccessful(SampleState.setValue1),
  tap(() => console.log('Success handler 3')),
  tap(() => this.emitter.action(SampleState.setValue3).emit(this.rdm()))
).subscribe();
```

The first handler correctly write to the console.
The second handler emit the `setValue2` action.
The third handler is never executed.

If I remove the emit from the 2nd handler, the third one is correctly executed.

Stackblitz : https://stackblitz.com/edit/ngxs-emitter-example-v6uhkr

I think this is related to #128.

**Comment by arturovt** [comment]
@mselerin it might be fixed by `2.0.0`, could you confirm?

**Comment by mselerin** [comment]
OK, I'll try it but I might not be able to test the new release before 15 days...
Wait & see...

**Comment by arturovt** [comment]
Just checked your example on the stackblitz and it seems to be working. I will close this issue. If you meet the issue again just leave a message here and I'll re-open.

**Comment by misterpy** [comment]
I've checked the stackblitz example and it does not work. Please have a look again by clicking the `doesn't work` button.

Only the last emitter is triggered correctly.
