### ISSUE TITLE
Emitter plugin not working properly with the latest NgXS/Store version

### ISSUE THREAD

**Issue by CheckMater** [ngxs-labs/emitter#158]
For some reason when injecting the Emitter service or when emitting an action using decorators the state gets changed to "undefined", it is working correctly using the Store 3.3.4 but when updating to 3.4.1 I get the error, please check this stackblitz:

https://stackblitz.com/edit/ngxs-emitter-error

Thanks in advance.

**Comment by splincode** [comment]
We need update to 3.4.0 and add integration tests

![image](https://user-images.githubusercontent.com/12021443/53955827-0d87b300-40eb-11e9-8032-9ef356b5e38a.png)

**Comment by splincode** [comment]
Fixed in 3.4.2

**Comment by splincode** [comment]
https://github.com/ngxs/store/issues/902

**Comment by Polyterative** [comment]
Whoa this made me swear for a good evening, just learning ngxs I thought I was missing something
