### ISSUE TITLE
ngxs-labs-emitter.js:81 Uncaught TypeError: Cannot set property 'update' of undefined

### ISSUE THREAD

**Issue by PivnovArtem** [ngxs-labs/emitter#30]
If I forgot to specify a static

![image](https://user-images.githubusercontent.com/35925144/47359324-257b0f00-d6d5-11e8-8568-c173942de93e.png)

![image](https://user-images.githubusercontent.com/35925144/47359095-7cccaf80-d6d4-11e8-8fe1-caf32c1972b5.png)

You have to do error handling.

**Comment by arturovt** [comment]
@PivnovArtem, mm, could you please describe what's happening? I mean does this error happen when you're trying to build your app (JIT/AOT)?

**Comment by PivnovArtem** [comment]
Observed behavior reproduce in JIT and AOT when if we not add `static` method!
