### ISSUE TITLE
Angular 9 dependency injection issue

### ISSUE THREAD

**Issue by mbouclas** [ngxs-labs/emitter#426]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ x] Other... Please describe:
</code>This is an Angular issue but looking for help here as this is the suggest way to user the emitter in the docs.</pre>

## Current behavior

```
export class BusinessState {
    private static businessService: BusinessService;
    private static userService: UserService;
    constructor(
        injector: Injector
    ) {
        BusinessState.businessService = injector.get<BusinessService>(BusinessService);
        BusinessState.userService = injector.get<UserService>(UserService);
    }
```
This no longer works in Angular 9, produces the following error
```
Can't resolve all parameters for BusinessState: (?).
    at getUndecoratedInjectableFactory (core.js:18801) [angular]
    at injectableDefOrInjectorDefFactory (core.js:18785) [angular]
    at providerToFactory (core.js:18851) [angular]
    at providerToRecord (core.js:18835) [angular]
    at R3Injector.processProvider (core.js:18651) [angular]
    at :5001/vendor.js:59157:38 [angular]
    at :5001/vendor.js:43540:76 [angular]
    at Array.forEach (<anonymous>) [angular]
    at deepForEach (core.js:1141) [angular]
    at R3Injector.processInjectorType (core.js:18612) [angular]
    at :5001/vendor.js:59134:30 [angular]
    at :5001/vendor.js:43540:76 [angular]
    at Array.forEach (<anonymous>) [angular]
    at deepForEach (core.js:1141) [angular]
```

## Environment

<pre><code>
Libs:
- @angular/core version:~9.0.0-rc.5
- @ngxs/store version: ^3.5.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.13.0
- Platform:  Windows

Others:

</code></pre>

**Comment by splincode** [comment]
please add stackblitz reproduce

**Comment by mbouclas** [comment]
The solution to this is to `@Injectable()` wherever you declare a state with `@State`. So now the code needs to look like so:
```
@Injectable()
@State<BusinessStateModel>({
....
```

**Comment by splincode** [comment]
@mbouclas https://www.ngxs.io/advanced/ivy-migration-guide
