### ISSUE TITLE
The error is constantly falling

### ISSUE THREAD

**Issue by splincode** [ngxs-labs/emitter#45]
![image](https://user-images.githubusercontent.com/12021443/48067233-cfcc5980-e1e0-11e8-90a7-617c512e57fd.png)

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/48069859-8fbca500-e1e7-11e8-8637-d6ac484bf7bb.png)

**Comment by splincode** [comment]
```1.0.3 - stable versions```

**Comment by ntdog22** [comment]
If I **`yarn add nanoid`**, can I use **`@ngxs-labs/emitter@1.2.1`**? I do not see the initial error you commented after adding that package manually.

**Comment by arturovt** [comment]
@ntdog22 If it works - I guess it's ok. But I think I have to find another solution of generating `id`, because this library (`nanoid`) has nodejs module resolution.
