### ISSUE TITLE
Not working with lazy load into ngxsOnInit

### ISSUE THREAD

**Issue by splincode** [ngxs-labs/emitter#48]
![image](https://user-images.githubusercontent.com/12021443/48124119-9fda9000-e28c-11e8-874e-c80202f30329.png)

![image](https://user-images.githubusercontent.com/12021443/48124134-a537da80-e28c-11e8-9bdc-e3cd5b394d43.png)

**Comment by arturovt** [comment]
@splincode предоставь, плиз, больше информации, как отловить у себя например

**Comment by arturovt** [comment]
@splincode я попробовал, все ок

**Comment by splincode** [comment]
Да, это должен быть лэйзи модуль
