### ISSUE TITLE
Error when making a POST request to an API returning Status 201 

### ISSUE THREAD

**Issue by ntdog22** [ngxs-labs/emitter#53]
When making a POST request for creating a new entity _**x,**_ using an injected service in my `entity.state.ts` file, an `Uncaught error`, with no details or further information, prevents the state from being persisted, even though the entity was successfully created / returned in the API response.

To make things more weird, intercepting the emittable with `ofEmittableErrored()` and logging the error to the console puts the API response payload as the value for the `error:` property, the emitted object from `createEntity.emit(inputObject)` as the value for the `payload:` property and sets the `type:` property to the `@Receiver({ type: x})` that I defined.

 The API POST is returning `201` whilst the other API calls (that I have not had any issues with) are returning `200`. 

Packages:
`"@ngxs-labs/emitter": "^1.3.0"`
`"@ngxs/store": "3.2.0-dev.master-e5e34c9"`
and tried with / without `"@ngxs-labs/immer-adapter": "^1.0.0"` but the error still occurs.

Using:
`"@angular/core": "7.0.3"`
`Node v10.13.0`
`Yarn 1.12.1`

Where the scribbled out portion after `Uncaught` is the API response.
![image](https://user-images.githubusercontent.com/6867405/48219429-59933880-e341-11e8-81cf-97a90698b1e0.png)

**Comment by arturovt** [comment]
@ntdog22 I'll try to have a look asap

**Comment by ntdog22** [comment]
@arturovt Thank you! If you need more information, please let me know. I can create a reduced test-case project if need be.

**Comment by splincode** [comment]
Please add stackblitz repro
