### ISSUE TITLE
@Select() of an @Receiver doesnt trigger change events

### ISSUE THREAD

**Issue by pdemilly** [ngxs-labs/emitter#71]
```
@Receiver()
    static showTrafficLayer ({ patchState }: StateContext<MapViewStateModel>, { payload }: EmitterAction<boolean>): void {
        patchState ({ showTrafficLayer: payload });
    }
```
Doesn't trigger changes to that property somewhere else in my code as defined with a Select decorator

```@Select(MapViewState.showTrafficLayer) showTrafficLayer$: Observable<boolean>;```

**Comment by splincode** [comment]
the receiver decorator is not designed for this

**Comment by arturovt** [comment]
the problem even is not in receiver, the `@Select` decorator wants to receive anonymous function | static method decorated with `@Selector` | state class reference or if there are no arguments passed - it takes your decorated property name

**Comment by pdemilly** [comment]
As a user of your package I believe it is a serious shortcoming and should be noted in the documentation. What prevent's it to be implemented? In the receiver code could it be hooked to the dispatch code of selector? (sorry haven't read the code yet)

I think your package is extremely valuable. One thing that becomes quickly apparent when using NgxsModule is the over abundance of Actions even for trivial task which is counter productive. I prefer to use emitter for simple actions and reserve @Action for things that stand up.  But I would expect that the end result is the same.

**Comment by splincode** [comment]
this violates the concept NGXS, unfortunately, it will not be implemented
