### ISSUE TITLE
Not workign with the v18.0.0 of the store 

### ISSUE THREAD

**Issue by vanerleo** [ngxs-labs/emitter#788]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

Throws error at compile time
```
✘ [ERROR] No matching export in "node_modules/@ngxs/store/fesm2022/ngxs-store.mjs" for import "ensureStoreMetadata"

    node_modules/@ngxs-labs/emitter/fesm2020/ngxs-labs-emitter.mjs:1:9:
      1 │ import { ensureStoreMetadata, Store, getActionTypeFromInstance } from '@ngxs/store';
```

## What is the motivation / use case for changing the behavior?

Throws error at compile time

## Environment

<pre><code>
Libs:
- @angular/core version: 18.0.2
- @ngxs/store version: 16.0.0

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alexej-strelzow** [comment]
Is this repo still maintained?

**Comment by SanderBreivik** [comment]
Any updates on this? @arturovt

**Comment by arturovt** [comment]
`6.0.0` has been published.

**Comment by alexej-strelzow** [comment]
thank you so much @arturovt !!!

**Comment by alexej-strelzow** [comment]
>  6.0.0 has been published.


@arturovt unfortunately the build is failing -> https://github.com/ngxs-labs/emitter/actions/runs/11516211565/job/32058429925

**Comment by arturovt** [comment]
It's building locally.

**Comment by alexej-strelzow** [comment]
I believe you, maybe you need to remove the following command: `yarn ngcc` from https://github.com/ngxs-labs/emitter/blob/master/.yarnrc.yml (afterInstall) ?

see
```
==========================================

ALERT: As of Angular 16, "ngcc" is no longer required and not invoked during CLI builds. You are seeing this message because the current operation invoked the "ngcc" command directly. This "ngcc" invocation can be safely removed.

A common reason for this is invoking "ngcc" from a "postinstall" hook in package.json.

In Angular 17, this command will be removed. Remove this and any other invocations to prevent errors in later versions.

==========================================
```

**Comment by arturovt** [comment]
You might consider doing it in a separate PR, as I currently don’t have the time to maintain this package.

**Comment by SanderBreivik** [comment]
I created a PR @arturovt: [PR](https://github.com/ngxs-labs/emitter/pull/790)
